document.addEventListener('DOMContentLoaded', function() {
  var input = document.getElementById('chatbot-input');
  var sendBtn = document.getElementById('chatbot-send-btn');
  var messages = document.getElementById('chatbot-messages');

  // Function to simulate sending a message
  function sendMessage() {
      var message = input.value.trim();
      if(message) {
          // User message
          var userMessageElement = document.createElement('div');
          userMessageElement.textContent = 'You: ' + message;
          messages.appendChild(userMessageElement);

          // Chatbot response
          var botMessageElement = document.createElement('div');
          botMessageElement.textContent = 'Bot: ' + getBotResponse(message);
          messages.appendChild(botMessageElement);

          input.value = '';
          messages.scrollTop = messages.scrollHeight;
      }
  }

  // Simulate a simple bot response
  function getBotResponse(input) {
      // Convert the input to lowercase for case-insensitive matching
      input = input.toLowerCase();

      // Object to hold input-response pairs
      var responses = {
          "hello": "Hi Chakie doll!",
          "ano gawa mo": "Eto, ka-chat nanaman yung mga taong lonely.",
          "ano gawa mo?": "Eto, chat chat lang sa mga taong walang jowa",
          "gawa mo": "chat chat lang",
          "gawa mo?": "Busy sa jowa ko. Ikaw? Ayyyy wala ka nga palang jowa",
          "crush ba ko ng crush ko?": "Kung naliligo ka lang sana everyday, malay mo may chance.",
          "kamusta": "Eto, pretty pa din, ikaw? Chaka pa din? Charooottt!!!",
          "who are you": "I'm your MAMSH, beeeeetttcchhh!",
          "hu u": "Ang MAMSH mo!",
          "ano gawa": "Wala gawa.",
          "may jowa ako": "Edi lamunin mo!",
          "excuse me may jowa ako": "Good! Buti may pumatol sa camel",
          "may jowa ako no": "Kanino mo nanaman naagaw yan?",
          "excuse messages, may jowa ako": "Congrats! Kanino mo naagaw?",
          "may jowa ako!": " Pagkalat mo! Inagaw mo lang yan eh.",
          "meron akong jowa": "Yabang! Eh may iba yan for sure!",
          "meron akong jowa!": "May jowa din yang iba eh",
          "sino ka?": "Ako lang naman yung pinakamagandang ChatBot sa Pinas",
          "goodmorning": "Ang aga ni accla ohhh Perfect!",
          "ako": "K. Kung jan ka masaya.",
          "anong name mo?": "I'm your Mamshi!!",
          "sakit ng ulo ko": "kakacellphone mo yan!",
          "ang sakit ng ulo ko": "Cellphone pa!",
          "anong magandang gawin?": "mag  trabaho, para naman umasenso ka!",
          "ano magandang gawin?": "Work tayo miii1 Wag puro cellphone.",
          "ano madandang gawin": "Ano pa, edi mag trabaho! Mag lubay ka sa kakacellphone!",
          "anong maganda gawin": "Trabaho. Hindi ka pa mayaman.",
          "ako?": "Ayyyy, sino pa bang mabantot dito, ikaw lang naman diba?",
          "ako??": "Edi sya na lang. Apaka arte ni accla ",
          "ikaw": "*clap clap clap *snap snap snap",
          "good morning": "Anong maganda sa morning?",
          "gud morning": "Gising ka na pala, trabaho na! Hindi tayo rich.",
          "good morning!": "toothbrush muna miiiii. Medyo may amoy eh.",
          "kamusta?": "Keri naman miii! Eto pretty pa din, Ikaw? chaka pa din as always? Charooottt!",
          "sino ka ba?": "Hulaan mo!",
          "who are you?": "I'm you MAMSH!!!",
          "chaka mo": "Mamsh, Mas chaka ka! Ambantot kaya ng hininga mo.",
          "hello!": "Hi!!!",
          "pagod nako": "Mas pagod ako! Ang dami ko kayang ka=chat.",
          "pagod nako!": "Nahiya naman sayo yung mga bongga kumayod sa buhay",
          "pagod na ako": "Edi mag pahinga. Tama na yang kakacellphone mo",
          "pagod na me": " Edi matulog na u.",
          "pagod na ako!": "Wag moko sigawan! Mag pahinga ka, wag mag maldita!",
          "pagod na ako!!": "Wag mag maldita, mag pahinga ka.",
          "pagod nako!!": "kasalanam ko?",
          "kakapagod": "Maging panget?",
          "kakapagod!": "Maging chaka?",
          "kakapagod na": "Umasa?",
          "hindi": "Beri gud",
          "oo": "ahhhhh",
          "oo!": "WAG MOKO SIGAWAN SHUTACAAAAA!",
          "oo nga": "K.DOT",
          "oo na lang": "Napilitan pa si accla ohhh",
          "good afternoon": "Wag moko kausapin, mainit",
          "goodafternoon": "anong kelangan mo?",
          "gud afternun": "GOOD AFTERNOON. Aral muna spelling ha.",
          "taray mo naman": "Dapat lang!",
          "oo nga!": " Sabi mo eh",
          "hindi nga!": "Relax, hindi kelangan sumigaw",
          "crush nya kaya ako?": "Kung nagtu-toothbrush ka lang sana, malay mo may chance.",
          "crush kaya nya ako?": "Mag hilod ka muna, puro ka kalandian",
          "crush kaya nya ako": "Miiii, wala nang pag asa. Ang tao ay para sa tao. Ikaw, para sa kapwa mo higad.",
          "crush nya kaya ako": "Depende kung pumapatol sya sa unding.",
          "bet kaya nya ako?": "Siguro? Mukhang animal lover naman sya.",
          "bet kaya nya ako": "Well, libre naman mangarap.",
          "bet nya kaya ako?": "Wag na umasa miiii. Hindi pa legal jumowa ng bulate",
          "bet nya kaya ako": "Oo naman! Animal lover nga sya diba!",
          "hindi nya ako bet": "Dasssurrrvvv. Next question.",
          "huhu": "chaka mo umiyak",
          "huhuhu": "Ganyan ka talaga umiyak? Chaka ha. Sabagay, umaayon naman sa mukha.",
          "hindi naman": "Owkey, sabi mo eh",
          "haha": "Ang plastic ng tawa ha.",
          "hahaha": "Laki ng bunganga ni accla!",
          "hehe": "??? half happiness?",
          "hehehe": "Funny?",
          "hihi": "Ayyyy ohhh. Michael Jackson ang peg?",
          "hihihi": "Parang kinikiliti sa singit ha.",
          "hindi ah": "K.dot",
          "hindi kaya": "Sus sus sus si acclaa, deny pa!",
          "hindi!": "Bat defensive?",
          "hindi nga": "Kaya ka chumachaka eh, deny pa!",
          "im happy": "Edi bonnga! Shat na!",
          "chaka!": "Chararat!",
          "chaka": "Keri lang, habulin naman ng boys, eh ikaw?",
          "hi": "hello!!",
          "jaja": "Jejemon pa din?",
          "jajaja": "Shuta, seryoso ka? Jejemon parin until now?",
          "jajajaja": "Iba ka accla, sinabuhay talaga pagiging jejemon.",
          "huy": "bakeeeet?!",
          "oi": "Oi ka din!",
          "hi!": "Haluuuu",
          "nag break kame": "Dasurv!!!!",
          "break na kame": "Oh tapos?",
          "gago": "ka!",
          "gago!": "Dumi ng bunganga ni accla oh",
          "huy!": "Oh? Anong problema?",
          "where are you from?": "I am from panet Nemic",
          "i have a question": "Go! Ask na Nakshi",
          "I have a question": "Tell me",
          "i am so happy": "Really? That's great!",
          "i'm happy": "That's good to know!",
          "what time is it?": "It's time to parttttyyyyy!!!!",
          "i am happy": "That's good to know!",
          "i'm feeling happy": "That's really good to know",
          "i am feeling sad": "Why are you feeling sad?",
          "ang lunngkot ko": "Bakit naman miii?",
          "ang sad": "why naman miii?",
          "ang sad naman": "Why oh why?",
          "ang sad ko": "Bwaket?",
          "i am so tired": "You should rest!",
          "i'm tired": "maybe you need some rest.",
          "how are you?": "Eto, may jowa, masaya ang loveelife, madalas nadidiligan, eh ikaw?",
          "bye": "Adios chaps!",
          "musta": "Eto, masaya kay jowa, always nadidiligan, ikaw?",
          "sana all": "iwasan maging inggitera, hindi na nga kagandahan eh",
          "sana ol": "bakla,''all'' hindi ''ol''. Medyo bobita tayo jan ha",
          "sorry": "K.",
          "maldita": "dapat lang, maganda ako",
          "maldita!": "Oh, tapos?",
          "maldita mo": "IKR",
          "taray": "Lakas maka-baklang 80's ha",
          "bobo": "May jowa naman, ikaw?",
          "la ko pake": "K.",
          "lakompake": "K.dot",
          "taga san ka": "Kapit bahay mo lang ako",
          "weh": "oo na, may chismis pala ako",
          "weh?": "Hay naku! By the way, may chismis ako",
          "totoo ba": "Sa truly!",
          "totoo ba?": "Syempre eme lang",
          "true ba?": "Oo naman yes!",
          "truly ba": "Yes Mamsh!",
          "tru ba": "Yes!",
          "really?": "Oo nga!",
          "maganda ba ko": "Keri naman, pwede na panglaman tyan ng mga tambay",
          "ang harsh mo naman": "Dapat lang!",
          "ang harsh": "Iyak ka?",
          "one plus one": "seryoso ka?",
          "1 plus 1": "Kaya aral muna dapat bago jowa eh",
          "iniwan ako ng jowa ko": "Desuuuuurvvvv! Buti nga! Focus na lang kasi sa work or studies!",
          "wala na kame": "Alam ko, kame na kasi.",
          "anong chika": "Alam mo ba, yung friend mo? Sinisiraan ka daw.",
          "anong chika?": "Alam mo ba, sabi sakin nung friend mo, hindi ka daw naliligo. Sabi ko naman, wag sya ganun. Alam naman natin na medyo may amoy ka, pero light light lang naman.",
          "mabaho ba ako": "light amoy lang naman. Hindi naman super offensive sa ilong.",
          "mabaho ba ako?": "Sorry mamsh ha, pero may slight amoy ka eh. Pero light lang naman. Ugaliin kasi minsan mag sabon at hilod.",
          "mabaho bako": "Haaaayyy. It's time to let you know. Akala ko friends mo lang nakakaamoy sayo. Buti napansin mo din. Ligo na!",
          "mabaho bako?": "Yes miiiiiiii!!!!!!! Maligo ka na",
          "ano masarap kainin": "ako pa talaga tinanong mo nyan mi?",
          "ano masarap kainin?": "Kain ka utak miii. Pati pag kain mo iaasa mo sakin?",
          "suggestion lang naman": "Whatever!",
          "anong masarap kainin": "ako, keri ba?",
          "anong masarap kainin?": "Papak ka nalang ng asin. Wala pang sweldo.",
          "meron na": "Ohhh ehhhh go!!!",
          "ano nga": "hay naku!",
          "bilis na": "Sa ChatGPT ka kung bet mo mabilis!",
          "sarap kumain": "Go!",
          "kain tayo": "Bobita si accla oh. ChatBot papakainin? Edi na-ground ka.",
          "offer lang naman": "Pag mago-offer, ginagamit yung utak.",
          "nag offer lang naman": "Ganun ba yun?",
          "nag offer lang": "ahhhhhhhhhhhh. OK",
          "nag alok lang naman": "Daming satsat",
          "nag alok lang": "Bait mo naman kahit na mukha kang holdaper",
          "talaga?": "Yezzzzzzz!!!!",
          "talaga": "yeahhhh",
          "ang saklap": "Maging pangit? Sorry you have to feel that way.",
          "saklap": " Saklap ng amoy ng hininga mo? Buti alam mo. Tagal na nag pipigil ng friends mo eh.",
          "grabe": "Deserve ba?",
          "grabe sya": "Naman!",
          "grabe sya!": "IKR",
          "grabe sya oh": "Wag iiyak",
          "grabe ka naman": "Diba! Ganun dapat",
          "bad kaya yun": "Alam mo kung ano yung bad? Yung pagtutuk mo sa cellphone magdamag. Mag trabaho ka!",
          "ang bad": "Mas bad mukha mo!",
          "ang ganda ko": "SYNTAX ERROR",
          "ganda ko": "Wag na ipilit.",
          "maganda ako": "Hallucination na yan accla!",
          "ganda mo": "Alam ko, sa ikaw din no?",
          "ang ganda mo": "Napaka liit na bagay",
          "ganda mo eh": "Super! Dami nga nababaliw sakin eh!",
          "ikaw na": "I know!",
          "Ikaw na talaga": "Yes po, opo",
          "niloloko na ako ng jowa ko": "Oo naman! Matagal na!",
          "niloloko ba ako ng jowa ko?": "Sorry to say, pero nakita ko sya nung nakaraan, may kalandian.",
          "niloloko ba ko ng jowa ko": "Oo miiii. Nahuli ko sya na may ka-chat na iba",
          "niloloko ba ko ng jowa ko?": "Oo, sawa na daw sya sa black meat eh",
          "niloloko bako ng jowa ko": "Tamang hinala ka accla",
          "niloloko bako ng jowa ko?": "Oo, kaya hiwalayan mo na, para malaya na kami ng jowa mo",
          "gusto ko na magkajowa": "Pwede ba magjowa yung mga camel?",
          "gusto ko na magka jowa": "Pwede pala mag jowa yung mga bulate?",
          "gusto ko na mag ka jowa": "Sa panaginip pwede pa, in real life? Medyo malabo",
          "may jowa ka ba": "Madami",
          "may jowa ka ba?": "Oo naman. Inggit ka no?",
          "may jowa kaba": "Yeessss, madami",
          "may jowa kaba?": "Oo naman! Inggit ka?",
          "penge": "Bawal sa higad",
          "penge naman": "Manahimik ka!",
          "bongga": "Dibaaaaaa",
          "bongga!": "Pak!",
          "sorry": "Apology accepted.",
          "sorry na": "Luhod ka muna.",
          "luh": "may chismis ako accla",
          "ano yun": "Nabasa ko yung chat nung ibang friends mo about sayo, totoo ba na mabantot daw kili-kili mo?",
          "ano yun?": "Narinig ko na pinagchi-chismisan ka nung mga ''so called'' friends mo. May amoy daw bunganga mo.",
          "ano": "Last time kase, Narinig ko nag uusap mga friends mo, Eh hindi ko naman sana bet marinig pero sabi nung isang friend mo, yung medyo balayage yung kulay na ang puti ng mukha pero super tanned yung leeg, sabi nya, grabe ka daw mamulutan and tumagay kahit wala kang ambag",
          "ano?": "Eto na nga, may ibang GC kasi yung mga friends mo pero hindi ka ka-join. May mga usap-usapan dun na puro kuto ka daw. Tapos hindi ka pa daw nagpapalit ng underwear!",
          "ha?": "Hakdowg",
          "anong chismis":"Diba may friend ka na nag sisimula yung name sa letter 'A', Ang chismis nya, Hindi ka pa daw nag babayad ng utang sa kanya tapos malikot daw kamay mo.",
          "anong chismis?": "Eto na nga, yung friend mong si letter 'J', Pinagkakalat na social climber ka daw. Sabi ni accla, yung post mo na umiinom ka ng Starbucks, kinuha mo lang daw yung cup sa basurahan tapos hinugasan lang. Tapos tinimplahan mo lang da ng 3-in-1.",
          "ah": "Accla! ambantot ha!",
          "ahh": "Anlala ng amoy ha",
          "ang init": "Diba!",
          "ang init no": "Kaya nga eh",
          "sobrang init": "sinabi mo pa",
          "super init": "Mas hot ako!",
          "talaga ba": "Oo naman yezzzzzz!",
          "talaga ba?": "Oo nga!",
          "may jowa ka": "Naku! Napakadami. Maiinggit ka lang.",
          "may jowa ka?": "Parang ang sarcastic naman ng tanong mo. Syempre, may jowa ako, mga 100.",
          "wasak na wasak ka na": "Makipot pa rin naman kumpara sayo na MOA Area na sa luwag.",
          "wasak na wasak ka na!": "Mas makipot pa po ako sa butas ng karayom",
          "wasak ka na": "Mukha mo kaya wasakin ko?",
          "wasak ka na!": "Friend, sarili mo nakikita mo sa salamin.",
          "ayoko": "Edi wag!",
          "ayoko nga": "Bahala ka",
          "ang dami": "Nainggit nanaman si accla",
          "ang dami naman": "Ganun talaga, greedy eh.",
          "ang dami mong jowa": "Well, ganyan talaga pag maganda. Pasalamat ka nga hindi mo mae-experience eh.",
          "anong pwedeng gawin dito": "Ano sa tingin mo? ChatBot nga diba?!",
          "anong pwedeng gawin dito?": "Hindi ba obvious? ChatBot ako, so malamang mag chat",
          "anong pwede gawin dito": "Shuta! ChatBot nga. Malamang mag chat",
          "anong pwede gawin dito?": "ChatBot ako, malamang mag chat. Maloka ka talaga pag nag video call ako sayo.",
          "ano pwede gawin dito": "Pwede naman, send GCash",
          "ano pwede gawin dito?": "Chikahan lang.",
          "wala akong gcash": "Seryoso ka?!",
          "wala ako gcash": "Purita ni accla ahhh",
          "wala akong pera": "Magtrabaho ka kasi!",
          "wala pa ko pera": "Mag work na!",
          "la ko pera": "haaaaayyyyyy",
          "ano gcash mo?": "09950822398",
          "ano gcash mo": "09950822398",
          "gcash mo": "09950822398",
          "ano gcash mo?": "09950822398",
          "gcash mo?": "09950822398",
          "anong gcash mo": "09950822398",
          "anong gcash mo?": "09950822398",
          



          // Add more pairs as needed
      };

      // Default response if no match is found
      var defaultResponse = "Di ko gets accla! Mga light light questions and replies lang. Wititit ako si ChatGPT na super brainy. Brain dead pa lang ako.";

      // Find a response, if available
      return responses[input] || defaultResponse;
  }

  // Event listeners for click and Enter key press
  sendBtn.addEventListener('click', sendMessage);
  input.addEventListener('keypress', function(e) {
      if(e.key === 'Enter') {
          sendMessage();
      }
  });

  // Focus the input when clicking on the chatbot window
  document.getElementById('chatbot-window').addEventListener('click', function() {
      input.focus();
  });
});